### web
server:
  port: 8081
  servlet:
    context-path: /gitegg-job-admin
spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: '@artifactId@'
  ### xxl-job-admin config
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  ### freemarker
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings.number_format: 0.##########
### mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml